# -*- coding: utf-8 -*-
"""matplotlib_basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A6vVCfXSr3K7usg_sjhakeC7_dS-Mz9-
"""

#importing libraries
import matplotlib.pyplot as plt

#importing numpy to get data for our plots
import numpy as np

x = np.linspace(0,10,100)
y = np.sin(x)
z = np.cos(x)

print(x)

print(z)

"""plotting the data"""

#sin wave
plt.plot(x,y)
plt.show()

# cosine wave
plt.plot(x,z)
plt.show()

# adding title x-axis & y-axis labels
plt.plot(x,y)
plt.xlabel('angle')
plt.ylabel('sine value')
plt.title('sine wave')
plt.show()

# parabola
x = np.linspace(-10,10,20)
y = x**2
plt.plot(x,y)
plt.show()

plt.plot(x, y, 'r+')
 plt.show()

plt.plot(x, y, 'g.')
plt.show()

plt.plot(x, y, 'rx')
plt.show()

x = np.linspace(-5,5,50)
plt.plot(x, np.sin(x), 'g-')
plt.plot(x, np.cos(x), 'r--')
plt.show()

#Bar plot 
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
languages = ['English','French','Spanish','Latin','German']
people = [100, 50, 150, 40, 70]
ax.bar(languages, people)
plt.xlabel('Languages')
plt.ylabel('Number of people')
plt.show()

#pie chart
fig1 = plt.figure()
ax = fig1.add_axes([0,0,1,1])
languages = ['English','French','Spanish','Latin','German']
people = [100,50,150,40,70]
ax.pie(people, labels=languages, autopct='%1.1f%%')
plt.show()

#Scatter plot
x = np.linspace(0,10,30)
y = np.sin(x)
z = np.cos(x)
fig2 = plt.figure()
ax = fig2.add_axes([0,0,1,1])
ax.scatter(x,y,color='g')
ax.scatter(x,z,color='b')
plt.show()

#3d scatter plot
fig3 = plt.figure()
ax = plt.axes(projection='3d')
z = 20 * np.random.random(100)
x = np.sin(z)
y = np.cos(z)
ax.scatter(x,y,c=z,cmap='Blues')
plt.show()

